package com.faculty.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.faculty.entity.Emp;
import com.faculty.repository.EmpRepository;
import com.faculty.service.SampleService;

@RestController
public class DemoController {

	@Autowired
	private SampleService s;
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private EmpRepository empRepository;
	
	@GetMapping(path="/")
	public String welcomeMessage()
	{
		return "Hi Welcome All";
	}
	
	@GetMapping(path="/ravi")
	public String getString()
	{
		return s.getString();
	}
	
	@GetMapping(path="/list")
	public List<String> getList()
	{
		return s.getList();
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Emp> getAllUsers() {
		// This returns a JSON or XML with the users
		return empRepository.findAll();
	}
}
